#!/bin/sh
#
# An example hook script for the "post-receive" event.
#
# The "post-receive" script is run after receive-pack has accepted a pack
# and the repository has been updated.  It is passed arguments in through
# stdin in the form
#  <oldrev> <newrev> <refname>
# For example:
#  aa453216d1b3e49e7f6f98441fa56946ddcd6a20 68f7abf4e6f922807889f52bc043ecd31b79f814 refs/heads/master
#
# see contrib/hooks/ for a sample, or uncomment the next line and
# rename the file to "post-receive".

#. /usr/share/git-core/contrib/hooks/post-receive-email
set -x

echo 1:$1
echo 2:$2
echo 3:$3

#oldrev=$(git rev-parse $1)
#newrev=$(git rev-parse $2)
#refname="$3"

set_rev_types() {
	newrev_type=$(git cat-file -t "$newrev" 2> /dev/null)
	oldrev_type=$(git cat-file -t "$oldrev" 2> /dev/null)
	if [ "$newrev" == "0000000000000000000000000000000000000000" ] ; then
		rev_type="$oldrev_type"
		rev="$oldrev"
	else
		rev_type="$newrev_type"
		rev="$newrev"
	fi
}

while read oldrev newrev refname
do
	set_rev_types
	case "$refname","$rev_type" in
	  refs/tags/*,tag)
	    curl http://127.0.0.1/git/notifyCommit?url=/opt/rctc-repo
	    # annotated tag
	    #refname_type="annotated tag"
	    #function="atag"
	    #short_refname=${refname##refs/tags/}
	    # change recipients
	    #if [ -n "$announcerecipients" ]; then
	    #  recipients="$announcerecipients"
	    #fi
	  ;;
	esac
done
